[package]
name = "postwomen"
version = "0.1.0"
authors = ["b1tg <b1tg@protonmail.ch>"]
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
pretty_env_logger = "0.3.0"
subprocess = "0.2.9"
serde_json = "1.0"